[robot]

name="Chomp"
initial_gait="Ripple"
forward_deadband = 0.05
angular_deadband = 0.05

[robot.geometry]

halfwidth=0.600

[robot.legs]

count=6
position_ramp_time=1.0
toe_position_tolerance=0.03
telemetry_frequency=10
telemetry_period_smoothing=0.9
support_pressure=7.0
desired_ride_height=-0.21
ride_height_gain=0.2

[robot.legs.joint_gain.Curl]
ProportionalGain=12
DerivativeGain=0
ForceDamping=20
FeedbackLowpass=0
[robot.legs.joint_gain.Swing]
ProportionalGain=12
DerivativeGain=0
ForceDamping=20
FeedbackLowpass=0
[robot.legs.joint_gain.Lift]
ProportionalGain=12
DerivativeGain=0
ForceDamping=20
FeedbackLowpass=0

[[robot.legs.description]]
name="LeftFront"
index=0
address=0x10
# X, Y, Z
origin=[0, 0, 0]
# Roll, pitch, yaw
orientation=[0, 0, 180]

[[robot.legs.description]]
name="LeftCenter"
index=1
address=0x20
# X, Y, Z
origin=[0, 0, 0]
# Roll, pitch, yaw
orientation=[0, 0, 180]

[[robot.legs.description]]
name="LeftRear"
index=2
address=0x30
# X, Y, Z
origin=[0, 0, 0]
# Roll, pitch, yaw
orientation=[0, 0, 180]

[[robot.legs.description]]
name="RightRear"
index=3
address=0x40
# X, Y, Z
origin=[0, 0, 0]
# Roll, pitch, yaw
orientation=[0, 0, 0]

[[robot.legs.description]]
name="RightCenter"
index=4
address=0x50
# X, Y, Z
origin=[0, 0, 0]
# Roll, pitch, yaw
orientation=[0, 0, 0]

[[robot.legs.description]]
name="RightFront"
index=5
address=0x60
# X, Y, Z
origin=[0, 0, 0]
# Roll, pitch, yaw
orientation=[0, 0, 0]

[[robot.steps]]

name="Square"

# phase, X, Y, Z
# phase is periodic on [0, 1.0)
# X - away from robot
# Y - along robot side
# Z - vertical
points=[
    { "phase"=0.0, "X"=0.19, "Y"= 0.070, "Z"=-0.230 },
    { "phase"=0.6, "X"=0.19, "Y"=-0.070, "Z"=-0.230 },
    { "phase"=0.7, "X"=0.19, "Y"=-0.070, "Z"=-0.170 },
    { "phase"=0.9, "X"=0.19, "Y"= 0.070, "Z"=-0.170 },
]

length=0.140

direction_swap_phase=[0.3, 0.8]
direction_swap_tolerance=0.01

[[robot.steps]]

name="Trapezoid"

# phase, X, Y, Z
# phase is periodic on [0, 1.0)
# X - away from robot
# Y - along robot side
# Z - vertical
points=[
    { "phase"=0.00, "X"=0.19, "Y"= 0.070, "Z"=-0.230 },
    { "phase"=0.84, "X"=0.19, "Y"=-0.070, "Z"=-0.230 },
    { "phase"=0.89, "X"=0.19, "Y"=-0.050, "Z"=-0.170 },
    { "phase"=0.95, "X"=0.19, "Y"= 0.050, "Z"=-0.170 },
]

length=0.140

direction_swap_phase=[0.42, 0.92]
direction_swap_tolerance=0.01

[[robot.gaits]]
name="Tripod"
step_name="Square"
step_cycles=1.0
leg_phase=[0.0, 0.5, 0.0, 0.5, 0.0, 0.5]

[[robot.gaits]]
# definition of stance and flight
# stance + flight = 1
# 5 legs on the ground
# 4*Δφ < stance
# 6th leg in the air
# 5*Δφ > stance
# 6th leg back on the ground before 5th leg picks up
# 4*Δφ + (1 - 5*Δφ) < stance
# implies
# 1 -  Δφ < stance
# stance / 5 < Δφ < stance / 4
# 4/5 < stance < 5/6
# Square stance=0.6, Nope!
# Trapezoid stance=0.84
# .164 < Δφ < .205
# 1 - Δφ < 0.82
# pick 0.166

name="Wave"
step_name="Trapezoid"
step_cycles=1
leg_phase=[0.0, 0.167, 0.333, 0.500, 0.667, 0.833]

[[robot.gaits]]
name="StarWave"
step_name="Trapezoid"
step_cycles=1
leg_phase=[0.0, 0.667, 0.333, 0.833, 0.167, 0.500]

[[robot.gaits]]
name="Ripple"
step_name="Trapezoid"
step_cycles=1
leg_phase=[0.0, 0.333, 0.666, 0.000, 0.333, 0.666]
