// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcm/stomp_control_radio.h"

static int __stomp_control_radio_hash_computed;
static uint64_t __stomp_control_radio_hash;

uint64_t __stomp_control_radio_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __stomp_control_radio_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__stomp_control_radio_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xd889b03cf44b1fa3LL
         + __float_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __stomp_control_radio_get_hash(void)
{
    if (!__stomp_control_radio_hash_computed) {
        __stomp_control_radio_hash = (int64_t)__stomp_control_radio_hash_recursive(NULL);
        __stomp_control_radio_hash_computed = 1;
    }

    return __stomp_control_radio_hash;
}

int __stomp_control_radio_encode_array(void *buf, int offset, int maxlen, const stomp_control_radio *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].axis, 8);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].toggle, 8);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].failsafe), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].no_data), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int stomp_control_radio_encode(void *buf, int offset, int maxlen, const stomp_control_radio *p)
{
    int pos = 0, thislen;
    int64_t hash = __stomp_control_radio_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __stomp_control_radio_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __stomp_control_radio_encoded_array_size(const stomp_control_radio *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __float_encoded_array_size(p[element].axis, 8);

        size += __int8_t_encoded_array_size(p[element].toggle, 8);

        size += __boolean_encoded_array_size(&(p[element].failsafe), 1);

        size += __boolean_encoded_array_size(&(p[element].no_data), 1);

    }
    return size;
}

int stomp_control_radio_encoded_size(const stomp_control_radio *p)
{
    return 8 + __stomp_control_radio_encoded_array_size(p, 1);
}

int __stomp_control_radio_decode_array(const void *buf, int offset, int maxlen, stomp_control_radio *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].axis, 8);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].toggle, 8);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].failsafe), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].no_data), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __stomp_control_radio_decode_array_cleanup(stomp_control_radio *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_decode_array_cleanup(p[element].axis, 8);

        __int8_t_decode_array_cleanup(p[element].toggle, 8);

        __boolean_decode_array_cleanup(&(p[element].failsafe), 1);

        __boolean_decode_array_cleanup(&(p[element].no_data), 1);

    }
    return 0;
}

int stomp_control_radio_decode(const void *buf, int offset, int maxlen, stomp_control_radio *p)
{
    int pos = 0, thislen;
    int64_t hash = __stomp_control_radio_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __stomp_control_radio_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int stomp_control_radio_decode_cleanup(stomp_control_radio *p)
{
    return __stomp_control_radio_decode_array_cleanup(p, 1);
}

int __stomp_control_radio_clone_array(const stomp_control_radio *p, stomp_control_radio *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_clone_array(p[element].axis, q[element].axis, 8);

        __int8_t_clone_array(p[element].toggle, q[element].toggle, 8);

        __boolean_clone_array(&(p[element].failsafe), &(q[element].failsafe), 1);

        __boolean_clone_array(&(p[element].no_data), &(q[element].no_data), 1);

    }
    return 0;
}

stomp_control_radio *stomp_control_radio_copy(const stomp_control_radio *p)
{
    stomp_control_radio *q = (stomp_control_radio*) malloc(sizeof(stomp_control_radio));
    __stomp_control_radio_clone_array(p, q, 1);
    return q;
}

void stomp_control_radio_destroy(stomp_control_radio *p)
{
    __stomp_control_radio_decode_array_cleanup(p, 1);
    free(p);
}

int stomp_control_radio_publish(lcm_t *lc, const char *channel, const stomp_control_radio *p)
{
      int max_data_size = stomp_control_radio_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = stomp_control_radio_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _stomp_control_radio_subscription_t {
    stomp_control_radio_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void stomp_control_radio_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    stomp_control_radio p;
    memset(&p, 0, sizeof(stomp_control_radio));
    status = stomp_control_radio_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding stomp_control_radio!!!\n", status);
        return;
    }

    stomp_control_radio_subscription_t *h = (stomp_control_radio_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    stomp_control_radio_decode_cleanup (&p);
}

stomp_control_radio_subscription_t* stomp_control_radio_subscribe (lcm_t *lcm,
                    const char *channel,
                    stomp_control_radio_handler_t f, void *userdata)
{
    stomp_control_radio_subscription_t *n = (stomp_control_radio_subscription_t*)
                       malloc(sizeof(stomp_control_radio_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 stomp_control_radio_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg stomp_control_radio LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int stomp_control_radio_subscription_set_queue_capacity (stomp_control_radio_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int stomp_control_radio_unsubscribe(lcm_t *lcm, stomp_control_radio_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe stomp_control_radio_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

