// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _stomp_control_radio_h
#define _stomp_control_radio_h

#ifdef __cplusplus
extern "C" {
#endif

#define STOMP_CONTROL_RADIO_AXES 8
#define STOMP_CONTROL_RADIO_TOGGLES 8
#define STOMP_CONTROL_RADIO_OFF -1
#define STOMP_CONTROL_RADIO_CENTER 0
#define STOMP_CONTROL_RADIO_ON 1

typedef struct _stomp_control_radio stomp_control_radio;
struct _stomp_control_radio
{
    float      axis[8];
    int8_t     toggle[8];
    int8_t     failsafe;
    int8_t     no_data;
};

/**
 * Create a deep copy of a stomp_control_radio.
 * When no longer needed, destroy it with stomp_control_radio_destroy()
 */
stomp_control_radio* stomp_control_radio_copy(const stomp_control_radio* to_copy);

/**
 * Destroy an instance of stomp_control_radio created by stomp_control_radio_copy()
 */
void stomp_control_radio_destroy(stomp_control_radio* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _stomp_control_radio_subscription_t stomp_control_radio_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * stomp_control_radio is received.
 */
typedef void(*stomp_control_radio_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const stomp_control_radio *msg, void *userdata);

/**
 * Publish a message of type stomp_control_radio using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int stomp_control_radio_publish(lcm_t *lcm, const char *channel, const stomp_control_radio *msg);

/**
 * Subscribe to messages of type stomp_control_radio using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is received.
 *                This function is invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
stomp_control_radio_subscription_t* stomp_control_radio_subscribe(lcm_t *lcm, const char *channel, stomp_control_radio_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by stomp_control_radio_subscribe()
 */
int stomp_control_radio_unsubscribe(lcm_t *lcm, stomp_control_radio_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int stomp_control_radio_subscription_set_queue_capacity(stomp_control_radio_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type stomp_control_radio into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to stomp_control_radio_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int stomp_control_radio_encode(void *buf, int offset, int maxlen, const stomp_control_radio *p);

/**
 * Decode a message of type stomp_control_radio from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with stomp_control_radio_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int stomp_control_radio_decode(const void *buf, int offset, int maxlen, stomp_control_radio *msg);

/**
 * Release resources allocated by stomp_control_radio_decode()
 * @return 0
 */
int stomp_control_radio_decode_cleanup(stomp_control_radio *p);

/**
 * Check how many bytes are required to encode a message of type stomp_control_radio
 */
int stomp_control_radio_encoded_size(const stomp_control_radio *p);

// LCM support functions. Users should not call these
int64_t __stomp_control_radio_get_hash(void);
uint64_t __stomp_control_radio_hash_recursive(const __lcm_hash_ptr *p);
int     __stomp_control_radio_encode_array(void *buf, int offset, int maxlen, const stomp_control_radio *p, int elements);
int     __stomp_control_radio_decode_array(const void *buf, int offset, int maxlen, stomp_control_radio *p, int elements);
int     __stomp_control_radio_decode_array_cleanup(stomp_control_radio *p, int elements);
int     __stomp_control_radio_encoded_array_size(const stomp_control_radio *p, int elements);
int     __stomp_control_radio_clone_array(const stomp_control_radio *p, stomp_control_radio *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
