// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcm/stomp_sensors_control.h"

static int __stomp_sensors_control_hash_computed;
static uint64_t __stomp_sensors_control_hash;

uint64_t __stomp_sensors_control_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __stomp_sensors_control_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__stomp_sensors_control_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x0550104bc7859579LL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __stomp_sensors_control_get_hash(void)
{
    if (!__stomp_sensors_control_hash_computed) {
        __stomp_sensors_control_hash = (int64_t)__stomp_sensors_control_hash_recursive(NULL);
        __stomp_sensors_control_hash_computed = 1;
    }

    return __stomp_sensors_control_hash;
}

int __stomp_sensors_control_encode_array(void *buf, int offset, int maxlen, const stomp_sensors_control *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].hammer_angle), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].turret_angle), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].throw_pressure), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].retract_pressure), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int stomp_sensors_control_encode(void *buf, int offset, int maxlen, const stomp_sensors_control *p)
{
    int pos = 0, thislen;
    int64_t hash = __stomp_sensors_control_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __stomp_sensors_control_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __stomp_sensors_control_encoded_array_size(const stomp_sensors_control *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __float_encoded_array_size(&(p[element].hammer_angle), 1);

        size += __float_encoded_array_size(&(p[element].turret_angle), 1);

        size += __float_encoded_array_size(&(p[element].throw_pressure), 1);

        size += __float_encoded_array_size(&(p[element].retract_pressure), 1);

    }
    return size;
}

int stomp_sensors_control_encoded_size(const stomp_sensors_control *p)
{
    return 8 + __stomp_sensors_control_encoded_array_size(p, 1);
}

int __stomp_sensors_control_decode_array(const void *buf, int offset, int maxlen, stomp_sensors_control *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].hammer_angle), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].turret_angle), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].throw_pressure), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].retract_pressure), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __stomp_sensors_control_decode_array_cleanup(stomp_sensors_control *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_decode_array_cleanup(&(p[element].hammer_angle), 1);

        __float_decode_array_cleanup(&(p[element].turret_angle), 1);

        __float_decode_array_cleanup(&(p[element].throw_pressure), 1);

        __float_decode_array_cleanup(&(p[element].retract_pressure), 1);

    }
    return 0;
}

int stomp_sensors_control_decode(const void *buf, int offset, int maxlen, stomp_sensors_control *p)
{
    int pos = 0, thislen;
    int64_t hash = __stomp_sensors_control_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __stomp_sensors_control_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int stomp_sensors_control_decode_cleanup(stomp_sensors_control *p)
{
    return __stomp_sensors_control_decode_array_cleanup(p, 1);
}

int __stomp_sensors_control_clone_array(const stomp_sensors_control *p, stomp_sensors_control *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_clone_array(&(p[element].hammer_angle), &(q[element].hammer_angle), 1);

        __float_clone_array(&(p[element].turret_angle), &(q[element].turret_angle), 1);

        __float_clone_array(&(p[element].throw_pressure), &(q[element].throw_pressure), 1);

        __float_clone_array(&(p[element].retract_pressure), &(q[element].retract_pressure), 1);

    }
    return 0;
}

stomp_sensors_control *stomp_sensors_control_copy(const stomp_sensors_control *p)
{
    stomp_sensors_control *q = (stomp_sensors_control*) malloc(sizeof(stomp_sensors_control));
    __stomp_sensors_control_clone_array(p, q, 1);
    return q;
}

void stomp_sensors_control_destroy(stomp_sensors_control *p)
{
    __stomp_sensors_control_decode_array_cleanup(p, 1);
    free(p);
}

int stomp_sensors_control_publish(lcm_t *lc, const char *channel, const stomp_sensors_control *p)
{
      int max_data_size = stomp_sensors_control_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = stomp_sensors_control_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _stomp_sensors_control_subscription_t {
    stomp_sensors_control_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void stomp_sensors_control_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    stomp_sensors_control p;
    memset(&p, 0, sizeof(stomp_sensors_control));
    status = stomp_sensors_control_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding stomp_sensors_control!!!\n", status);
        return;
    }

    stomp_sensors_control_subscription_t *h = (stomp_sensors_control_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    stomp_sensors_control_decode_cleanup (&p);
}

stomp_sensors_control_subscription_t* stomp_sensors_control_subscribe (lcm_t *lcm,
                    const char *channel,
                    stomp_sensors_control_handler_t f, void *userdata)
{
    stomp_sensors_control_subscription_t *n = (stomp_sensors_control_subscription_t*)
                       malloc(sizeof(stomp_sensors_control_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 stomp_sensors_control_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg stomp_sensors_control LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int stomp_sensors_control_subscription_set_queue_capacity (stomp_sensors_control_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int stomp_sensors_control_unsubscribe(lcm_t *lcm, stomp_sensors_control_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe stomp_sensors_control_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

